name: Deploy to S3

on:
  push:
    branches:
      - main
      - ChristianBranch2
      
env:
  S3_BUCKET: ror-crl-revature
  AWS_REGION: us-east-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          
          
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "build/"
